import pygame
import Donnees as dn



font={}
font["a"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\a.png").convert()
font["A"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\amaj.png").convert()
font["b"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\b.png").convert()
font["B"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\bmaj.png").convert()
font["c"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\c.png").convert()
font["C"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\cmaj.png").convert()
font["d"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\d.png").convert()
font["D"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\dmaj.png").convert()
font["e"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\e.png").convert()
font["E"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\emaj.png").convert()
font["f"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\f.png").convert()
font["F"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\fmaj.png").convert()
font["g"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\g.png").convert()
font["G"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\gmaj.png").convert()
font["h"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\h.png").convert()
font["H"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\hmaj.png").convert()
font["i"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\i.png").convert()
font["I"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\imaj.png").convert()
font["j"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\j.png").convert()
font["J"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\jmaj.png").convert()
font["k"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\k.png").convert()
font["K"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\kmaj.png").convert()
font["l"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\l.png").convert()
font["L"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\lmaj.png").convert()
font["m"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\m.png").convert()
font["M"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\mmaj.png").convert()
font["n"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\n.png").convert()
font["N"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\nmaj.png").convert()
font["o"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\o.png").convert()
font["O"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\omaj.png").convert()
font["p"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\p.png").convert()
font["P"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\pmaj.png").convert()
font["q"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\q.png").convert()
font["Q"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\qmaj.png").convert()
font["r"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\r.png").convert()
font["R"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\rmaj.png").convert()
font["s"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\s.png").convert()
font["S"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\smaj.png").convert()
font["t"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\t.png").convert()
font["T"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\tmaj.png").convert()
font["u"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\u.png").convert()
font["U"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\umaj.png").convert()
font["v"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\v.png").convert()
font["V"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\vmaj.png").convert()
font["w"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\w.png").convert()
font["W"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\wmaj.png").convert()
font["x"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\x.png").convert()
font["X"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\xmaj.png").convert()
font["y"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\y.png").convert()
font["Y"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\ymaj.png").convert()
font["z"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\z.png").convert()
font["Z"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\zmaj.png").convert()
font["0"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\0.png").convert()
font["1"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\1.png").convert()
font["2"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\2.png").convert()
font["3"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\3.png").convert()
font["4"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\4.png").convert()
font["5"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\5.png").convert()
font["6"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\6.png").convert()
font["7"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\7.png").convert()
font["8"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\8.png").convert()
font["9"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\9.png").convert()
font["."]=pygame.image.load(dn.dossier+"Images\\Alphabet\\point.png").convert()
font[","]=pygame.image.load(dn.dossier+"Images\\Alphabet\\virgule.png").convert()
font["!"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\point d'exclamation.png").convert()
font["?"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\point d'interrogation.png").convert()
font["'"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\apostrophe.png").convert()
font["à"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\à.png").convert()
font["é"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\é.png").convert()
font["è"]=pygame.image.load(dn.dossier+"Images\\Alphabet\\è.png").convert()
font[" "]=pygame.image.load(dn.dossier+"Images\\Alphabet\\espace.png").convert()

for s in font:
    font[s].set_colorkey(dn.BLACK)

def tracer_message(screen,message,x,y):
    x_im, y_im=x,y
    for c in message:
        screen.blit(font[c],[x_im,y_im])
        x_im+=font[c].get_width()+4